package customApplicationPanel2.ui;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Insets;
import java.awt.Toolkit;
import javax.swing.JComponent;
import javax.swing.JSplitPane;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 *
 * @author om
 */
public class MainFrame extends javax.swing.JFrame {
	private static final Logger logger = LoggerFactory.getLogger(MainFrame.class);
    /**
     * Creates new form MainFrame
     * @throws java.lang.ClassNotFoundException
     */
    public MainFrame() {
    	logger.info("main frame");
        initComponents();
        
        //size of the screen
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);
        
        //height of the task bar
        Insets scnMax = Toolkit.getDefaultToolkit().getScreenInsets(getGraphicsConfiguration());
        int taskBarSize = scnMax.bottom;
        //available size of the screen 
        setSize(screenSize.width, screenSize.height - taskBarSize);
        
        this.statusBar = new StatusBarPanel();
        this.statusBar.setSize(getWidth(), 33);
        this.statusBar.setBounds(0, getHeight() - 33, getWidth(), 33);
        add(this.statusBar, BorderLayout.SOUTH);
        
        
        getSplitPane().setSize(getWidth(), getHeight() - this.statusBar.getHeight());
        
        getSplitPane().setMinimumSize(new Dimension(200, getHeight() - this.statusBar.getHeight()));
        getSplitPane().setMaximumSize(new Dimension(getWidth(), getHeight() - this.statusBar.getHeight()));
        
        setVisible(true);
    }

    public final JSplitPane getSplitPane() {
        return splitPane;
    }
    
    public void setLeftView(JComponent panel)
    {
        leftRootView.removeAll();
        leftRootView.add(panel, BorderLayout.CENTER);
    }

    public void setRightView(JComponent panel)
    {
    	logger.info("set right view");
        rightRootView.removeAll();
        rightRootView.add(panel, BorderLayout.CENTER);
        
        Dimension d = rightRootView.getSize();
        Dimension d1 = panel.getSize();
        Dimension d3 = rightRootView.getComponent(0).getSize();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        leftRootView = new javax.swing.JPanel();
        rightRootView = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        splitPane.setDividerLocation(200);

        leftRootView.setLayout(new java.awt.BorderLayout());
        splitPane.setLeftComponent(leftRootView);

        rightRootView.setLayout(new java.awt.BorderLayout());
        splitPane.setRightComponent(rightRootView);

        getContentPane().add(splitPane, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    /*
    public static void main(String args[]) {
       
    	logger.info("main frame");
       

       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
*/
    private StatusBarPanel statusBar;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel leftRootView;
    private javax.swing.JPanel rightRootView;
    private javax.swing.JSplitPane splitPane;
    // End of variables declaration//GEN-END:variables
}